security:
    encoders:
        Yoda\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        clients:
            entity: { class: UserBundle:User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/product/new, roles: ROLE_ADMIN }
        - { path: ^/product/new, roles: ROLE_ADMIN }
        - { path: ^/product/create, roles: ROLE_ADMIN }
        - { path: ^/product/.*/edit, roles: ROLE_ADMIN }
        - { path: ^/product/.*/update, roles: ROLE_ADMIN }
        - { path: ^/product/.*/delete, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
