security:
    encoders:
        Yoda\UserBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [clients, in_memory]
        clients:
            entity: { class: UserBundle:User }
        in_memory:
            memory:
                users:
                    olus: { password: karmapapa, roles: [ 'ROLE_ADMIN' ]  }
                    adi: { password: baniak, roles: [ 'ROLE_ADMIN' ]  }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/product/.*/show, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/product/, roles: ROLE_ADMIN }
        - { path: ^/orders/, roles: ROLE_ADMIN }
        - { path: ^/.*/new, roles: ROLE_ADMIN }
        - { path: ^/.*/create, roles: ROLE_ADMIN }
        - { path: ^/.*/.*/edit, roles: ROLE_ADMIN }
        - { path: ^/.*/.*/update, roles: ROLE_ADMIN }
        - { path: ^/.*/.*/delete, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
